# Generated by Django 5.2.4 on 2025-07-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablecars',
            name='desc',
            field=models.CharField(default=''),
        ),
    ]
