# Generated by Django 5.2.4 on 2025-07-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_availablecars_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecars',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
